job:
  environment:
    S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    WA_TASK_MONITOR_SERVICE_URL: "http://wa-task-monitor-aat.service.core-compute-aat.internal"
  # Don't modify below here
  image: ${IMAGE_NAME}
